### PR TITLE
Implement movable character

### LINKED ISSUE #9: Implement movable character

### PR DESCRIPTION
**Pull request by pparuzel**
Resolves #9

### CODE REVIEW

**Review by fturek — COMMENTED** [review]
@reconndev 
It looks good for me. 
However, there I have comments not to implementing character movement: 
Name branches differently to know what they are doing (e.x player_move_impl will be better option).
I encourage you to use lowerCamelCase for variables, not snake_case. 
I suggest you rename and split some functions, like `preload()` to `preloadPlayer()` and `preloadWorld()` (or just split this method to smaller ones). Same situation with `create()` method. 
I hope that this will improve readability of code.  

What is more, I think that it will be a good idea to use const variables to links/other files locations (also maybe in separate file?).
What do you think about splitting `game.js` file into smaller ones?

**Comment by pparuzel** [comment]
Create and Preload are library functions. At first we need only a game skeleton so there is no need for refactoring so early. We'll split files when the code gets bigger.
_"Name branches differently to know what they are doing"_ -> `player_impl` -> player implementation, which is meaningful enough I would say. This branch has the general player implementation.

I'll correct the snake case (C++/Python habits)

**Comment by pparuzel** [comment]
Snake case corrected

**Review by fturek — APPROVED** [review]
LGTM

**Pull request merged**
